- defaults:
    link:
      create: true
      relink: true
    clean:
      force: true

- shell:
    - ["git submodule update --init --recursive --remote", "Installing submodules"]

- clean: [
    '~',
    '~/.config',
]
